### PR TITLE
Feature/recheck web properties

### PR DESCRIPTION
**Pull request by Creepow**
*Before submission, please check that ...*

- [ ] the code follows the [Clean Code](https://clean-code-developer.com/) guidelines.
- [ ] the necessary tests are either created or updated.
- [ ] all status checks (Travis CI, SonarCloud, etc.) pass.
- [ ] your commit history is cleaned up.
- [ ] you updated the changelog.
- [ ] you updated necessary documentation within [retest/docs](https://github.com/retest/docs).

## Description
Draft PR to decide whether or not we use owner to manage our properties.
> TL;DR 

Needs the change in recheck.

### CODE REVIEW

**Comment by beatngu13** [comment]
Adapted this PR based on https://github.com/retest/recheck/pull/538.

The only thing we still have to think about: There is now `RecheckProperties` and RecheckWebProperties`. While recheck is working with the former, recheck-web uses latter. But in this case, do their live two instances?

**Comment by diba1013** [comment]
> While recheck is working with the former, recheck-web uses latter. But in this case, do their live two instances

Instead of treating them as extension (i.e. `RecheckWebProperties extends RecheckProperties`) and since extension does not really work with owner, we could treat them as real separate properties that just happen to be read from the same file.

**Comment by beatngu13** [comment]
The updated recheck snapshot now includes Rhino, which fails here:

https://travis-ci.com/retest/recheck-web/builds/139369773#L3426

**Comment by beatngu13** [comment]
@diba1013 @roesslerj please note https://github.com/retest/recheck-web/pull/443/commits/77a013fe5434bef62e22f068b5ab850ed0d42517.

**Pull request merged**
