### PR TITLE
If we didn't address the performance, at least we need to tell people …

### PR DESCRIPTION
**Pull request by roesslerj**
…we know how to fix it...

Please approve whoever sees it first :-)

### CODE REVIEW

**Comment by diba1013** [comment]
We will do a new release Soon&trade;. Part of #424 will be to document this, thus I do not think this is necessary, as this PR would have to be reverted partly.

**Comment by roesslerj** [comment]
We want to be fast. This _MUST_ be one of our key goals.
Therefore we must change things fast. This is one of the reasons we have rebazer and automation pipeline.
It _DO NOT ACCEPT_ that we have to discuss a mere 53 word, non-risk, documentation change. If you found a bug (which would be a spelling error), please comment. Otherwise please _APPROVE_ as we need to move forward. If #424 addresses and documents this, great. But until then (and you said it yourself "soon"), we need to get _SHIT DONE_ and at the _very least_ tell people what is going on.

**Comment by roesslerj** [comment]
This behavior in general makes PRs burdensome, which is _the opposite_ of what we want. We want fast, smooth, small changes, as little overhead as possible and we want people to take action and fix stuff. We need to talk about this culture of stall immediately.

**Comment by beatngu13** [comment]
>It [sic!] DO NOT ACCEPT that we have to discuss a mere 53 word, non-risk, documentation change.

Calm down. This is not how we want to deal with reviewer comments:

https://github.com/google/eng-practices/blob/master/review/developer/handling-comments.md

As you said, it is a documentation change. We can figure out a solution.

**Pull request merged**
