### PR TITLE
Exposing wrapped WebElement.

### PR DESCRIPTION
**Pull request by javydreamercsw**
Solve issue #288.

I was surprised/shocked to see the 1.3.0 branch not merged into master when it is released already. Merging into that branch since it's the most up to date.

### CODE REVIEW

**Comment by roesslerj** [comment]
Hello Javier Ortiz! Thank you for your PR. We have two automation solutions in place ... that obviously don't work well yet. We'll reopen the PR ... sorry.

**Comment by roesslerj** [comment]
Hello again!

Two options: Could you either address the issues stated by the cla-bot and reopen the PR towards the master branch, or are you fine with me copy/pasting the 3 lines change and reference you in the commit message? Whatever you prefer...

**Comment by roesslerj** [comment]
Reopened as https://github.com/retest/recheck-web/pull/293

**Comment by javydreamercsw** [comment]
I'm fine with the copy and paste solution.

**Pull request closed without merging**
