### PR TITLE
Feature/i frame handling

### PR DESCRIPTION
**Pull request by roesslerj**

### CODE REVIEW

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by beatngu13** [comment]
Please manually rebase.

**Pull request closed without merging**
