### PR TITLE
Feature/implement issue 389

### PR DESCRIPTION
**Pull request by briemla**
*Before submission, please check that ...*

- [x] the code follows the [Clean Code](https://clean-code-developer.com/) guidelines.
- [x] the necessary tests are either created or updated.
- [x] all status checks (Travis CI, SonarCloud, etc.) pass.
- [x] your commit history is cleaned up.
- [ ] you updated the changelog.
- [ ] you updated necessary documentation within [retest/docs](https://github.com/retest/docs).

## Description

> Support more complex CSS selectors when healing tests.

This is a partial implementation of issue #389. It supports all attribute selectors specified at [w3schools](https://www.w3schools.com/cssref/css_selectors.asp) and the following pseudo class selectors: `:checked`, `:disabled` and `:read-only`

### State of this PR

This PR does not support pseudo class selectors except `:checked`, `:disabled` and `:read-only`.

### Additional Context

### CODE REVIEW

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by beatngu13** [comment]
Will close this until merge issues have been resolved.

**Pull request closed without merging**
